Repository stolostron/grc-ui, pull requests merged in 2021-08, with the labels that each got.

#720 Remove Travis config and update for Prow ClusterPools
  .travis.yml
  CONTRIBUTING.md
  Dockerfile.e2etest
  README.md
  SECURITY.md
  build/rbac-setup.sh
  build/run-e2e-tests.sh
  build/setup-dev.sh
  setup-env.sh
Labels: lgtm, approved, dco-signoff: yes

#721 Update to use ui-components with VWT out of AcmHeader
  package-lock.json
  package.json
  tests/cypress/support/welcome_and_header.js
  tests/cypress/tests/welcomePage_and_Header.spec.js
Labels: lgtm, approved, dco-signoff: yes

#723 Update the expected message on iampolicies
  tests/cypress/config/violation-patterns.yaml
Labels: lgtm, approved, dco-signoff: yes

#710 [release-2.3] Skip RBAC tests on ROSA clusters
  build/rbac-setup.sh
  build/run-docker-tests.sh
  package.json
  tests/cypress/start_cypress_tests.sh
Labels: lgtm, approved, dco-signoff: yes

#727 Update packages 2.3
  package-lock.json
Labels: lgtm, dco-signoff: yes

#728 Restore @extended exclusion for PRs
  build/run-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#726 Update packages
  package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#729 Clean up references to old master branch
  tests/cypress/README.md
Labels: lgtm, approved, dco-signoff: yes

#732 Delete policy should also delete its policy automation
  src-web/components/modals/RemoveResourceModal.js
  tests/jest/components/modals/ModalsTestingData.js
  tests/jest/components/modals/RemoveResourceModal.test.js
  tests/jest/components/modals/__snapshots__/RemoveResourceModal.test.js.snap
Labels: approved, dco-signoff: yes

#735 Add path to redirect to oauth for RBAC check
  build/rbac-setup.sh
  tests/cypress/support/views.js
Labels: lgtm, approved, dco-signoff: yes

#737 Update E2E RBAC flows
  build/rbac-setup.sh
  tests/cypress/start_cypress_tests.sh
  tests/cypress/support/commands.js
  tests/cypress/support/views.js
  tests/cypress/tests/RBAC.spec.js
  tests/cypress/tests/all_policies_summary_table.spec.js
Labels: lgtm, approved, dco-signoff: yes

#739 Close automation modal if it's open
  tests/cypress/support/views.js
Labels: lgtm, approved, dco-signoff: yes

#740 Clean hub post-test
  build/run-docker-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#741 Fix "directory not found" error
  build/rbac-clean.sh
  build/run-docker-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#730 Patch cluster with `latest-<version>`
  build/cluster-setup.sh
  build/patches/certpolicyctrl
  build/patches/iampolicyctrl
  build/patches/policyctrl
  build/run-e2e-tests.sh
  build/wait_for.sh
Labels: lgtm, approved, dco-signoff: yes

#748 Fix canary patching
  build/cluster-patch.sh
  build/cluster-setup.sh
  build/run-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes
