Repository stolostron/grc-ui, pull requests merged in 2021-06, with the labels that each got.

#634 use white background for editor
  src-web/scss/common.scss
Labels: approved, dco-signoff: yes, lgtm

#632 update NPM packages to the latest
  Dockerfile.e2etest
  app.js
  jest.config.js
  package-lock.json
  package.json
  webpack.config.js
  webpack.dll.js
Labels: approved, dco-signoff: yes, lgtm

#635 fix cypress start warning
  Dockerfile.e2etest
  tests/cypress/start_cypress_tests.sh
  webpack.config.js
Labels: approved, dco-signoff: yes, lgtm

#637 Fix z-level of secondary header
  src-web/scss/common.scss
Labels: approved, dco-signoff: yes, lgtm

#636 disallow name/namespace change in edit mode
  src-web/components/common/TemplateEditor/TemplateEditor.js
  tests/cypress/support/commands.js
  tests/cypress/support/tests.js
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#641 use url from cypress config so mock works on cluster
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#642 Ansible Modal Stylish and polish
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/nls/platform.properties
  src-web/scss/ansible-modal.scss
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#644 Extra variables editor Stylish
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/scss/ansible-modal.scss
Labels: approved, dco-signoff: yes, lgtm

#643 mock empty credentials check in case other canary tests have added creds
  tests/cypress/support/views.js
  tests/cypress/tests/ansible_automation.spec.js
Labels: approved, dco-signoff: yes, lgtm

#646 fix-delete-action-in-extra_vars
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/nls/platform.properties
  tests/cypress/support/views.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#649 only run automation e2e test on local cluster
  tests/cypress/config/automation/clean_up.yaml
  tests/cypress/config/automation/create_credential.yaml
  tests/cypress/config/automation/create_subscription.yaml
  tests/cypress/config/automation/policy_toBeAutomated.yaml
  tests/cypress/config/automation/verify_run_manual.yaml
  tests/cypress/config/automation/verify_run_once.yaml
Labels: approved, dco-signoff: yes, lgtm

#648 update the operator subscription so default channel is used
  src-web/components/common/templates/spec-imagemanifestvuln.yaml
  tests/cypress/config/policy_YAML_templates_verification/ImageManifestVulnPolicy-raw.yaml
  tests/jest/components/common/CommonTestingData.js
Labels: approved, dco-signoff: yes, lgtm

#650 increase timeout when checking for automation history
  tests/cypress/tests/ansible_automation.spec.js
Labels: approved, dco-signoff: yes, lgtm

#647 [release-2.1] fix hardcode namespace in 2.1 branch
  build/run-docker-tests.sh
  build/run-e2e-tests.sh
Labels: dco-signoff: yes, lgtm

#655 increase automation timeout further
  tests/cypress/tests/ansible_automation.spec.js
Labels: approved, dco-signoff: yes, lgtm

#656 Update error handling
  app.js
  src-web/containers/AcmGrcPage.js
  src-web/containers/CreationTab.js
Labels: approved, dco-signoff: yes, do-not-merge/hold, lgtm

#657 redirect to welcome from base and /multicloud
  server/controllers/index.js
  tests/cypress/tests/welcomePage_and_Header.spec.js
Labels: approved, dco-signoff: yes, lgtm

#652 Prompt user to install Ansible Operator in modal
  jest.config.js
  server/lib/server/ansibleOperatorLink.js
  src-web/components/common/Modal.js
  src-web/components/modals/AnsibleAutomationModal/AnsibleAutomationModal.js
  src-web/components/modals/AnsibleAutomationModal/AnsibleOperatorNotInstalled.js
  src-web/nls/platform.properties
  src-web/utils/client/queries.js
  tests/cypress/support/commands.js
  tests/cypress/support/views.js
  tests/cypress/tests/ansible_automation.spec.js
  tests/jest/components/modals/AnsibleOperatorNotInstalled.test.js
  tests/jest/components/modals/__snapshots__/AnsibleOperatorNotInstalled.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#662 temporarily disable format apps dropdown e2e test case
  Dockerfile.e2etest
  package-lock.json
  package.json
  tests/cypress/tests/welcomePage_and_Header.spec.js
Labels: approved, dco-signoff: yes, lgtm

#664 fix-governance-policy-framework-e2e-test
  tests/cypress/tests/ImageManifest_governance.spec.js
  tests/cypress/tests/LimitRange_governance.spec.js
Labels: approved, dco-signoff: yes, lgtm

#668 disble-RHACM4K-1724
  tests/cypress/tests/Pod_governance.spec.js
Labels: approved, dco-signoff: yes, lgtm

#669 disable RHACM4K-1725
  tests/cypress/tests/IamPolicy_governance.spec.js
  tests/cypress/tests/ImageManifest_governance.spec.js
  tests/cypress/tests/LimitRange_governance.spec.js
  tests/cypress/tests/Namespace_governance.spec.js
  tests/cypress/tests/PodSecurityPolicy_governance.spec.js
  tests/cypress/tests/Pod_governance.spec.js
  tests/cypress/tests/RoleBindingPolicy_governance.spec.js
  tests/cypress/tests/RolePolicy_governance.spec.js
  tests/cypress/tests/SCCPolicy_governance.spec.js
  tests/cypress/tests/demos/ImageManifest_governance.spec.js
  tests/cypress/tests/demos/two_policies.spec.js
  tests/cypress/tests/demos/two_specs_policy.spec.js
Labels: approved, dco-signoff: yes, lgtm

#670 disable-Welcome-page-e2e-test
  tests/cypress/tests/welcomePage_and_Header.spec.js
Labels: approved, dco-signoff: yes, lgtm

#673 re-enable-Welcome-page-e2e-test
  package-lock.json
  package.json
  tests/cypress/tests/welcomePage_and_Header.spec.js
Labels: approved, dco-signoff: yes, lgtm

#659 Build fix
  build/run-e2e-tests.sh
Labels: approved, dco-signoff: yes, lgtm

#674 Re-enable tests
  tests/cypress/tests/IamPolicy_governance.spec.js
  tests/cypress/tests/ImageManifest_governance.spec.js
  tests/cypress/tests/LimitRange_governance.spec.js
  tests/cypress/tests/Namespace_governance.spec.js
  tests/cypress/tests/PodSecurityPolicy_governance.spec.js
  tests/cypress/tests/Pod_governance.spec.js
  tests/cypress/tests/RoleBindingPolicy_governance.spec.js
  tests/cypress/tests/RolePolicy_governance.spec.js
  tests/cypress/tests/SCCPolicy_governance.spec.js
  tests/cypress/tests/ansible_automation.spec.js
  tests/cypress/tests/demos/ImageManifest_governance.spec.js
  tests/cypress/tests/demos/two_policies.spec.js
  tests/cypress/tests/demos/two_specs_policy.spec.js
Labels: approved, dco-signoff: yes, lgtm

#676 fix time stamp in e2e test
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#651 [release-2.2] manual cherry pick of 628
  tests/cypress/start_cypress_tests.sh
Labels: dco-signoff: yes, do-not-merge/hold

#645 [release-2.2] fix hardcode namespace issue when getting acm route
  build/run-docker-tests.sh
  build/run-e2e-tests.sh
Labels: dco-signoff: no

#680 Fix editor overflow issues
  src-web/components/common/TemplateEditor/scss/template-editor.scss
Labels: approved, dco-signoff: yes, lgtm
