Repository stolostron/grc-ui, pull requests merged in 2021-04, with the labels that each got.

#537 reorg test
  tests/cypress/tests/CertPolicy_governance.spec.js
  tests/cypress/tests/IamPolicy_governance.spec.js
  tests/cypress/tests/Pod_governance.spec.js
  tests/cypress/tests/issue3677_wrong_namespaceSelector.spec.js
  tests/cypress/tests/issue7520_added_removed_namespaces.spec.js
Labels: approved, lgtm

#538 switch to use ACMPageHeader for all policies page
  jest.config.js
  lib/shared/constants.js
  package-lock.json
  package.json
  scss/common.scss
  scss/header-carbon-v9-migration.scss
  scss/module-grc-cards.scss
  src-web/components/common/RefreshTimeSelect.js
  src-web/containers/AllPolicies.js
  src-web/containers/App.js
  src-web/containers/GrcRouter.js
  src-web/containers/Welcome.js
  tests/cypress/support/commands.js
  tests/cypress/support/views.js
  tests/jest/components/modules/__snapshots__/PolicyClusterDetail.test.js.snap
Labels: approved

#542 update test case snapshot
  tests/jest/components/common/__snapshots__/PatternFlyTable.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyStatusView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyTemplateDetailsView.test.js.snap
Labels: approved, lgtm

#540 Use native `should` function - 11108
  tests/cypress/README.md
  tests/cypress/start_cypress_tests.sh
  tests/cypress/support/commands.js
Labels: approved, lgtm

#541 swtich all pages to use AcmPageHeader
  jest.config.js
  nls/platform.properties
  scss/policy-status-tab.scss
  scss/policy-status-view.scss
  scss/welcome.scss
  src-web/actions/index.js
  src-web/actions/login.js
  src-web/components/common/Page.js
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/modules/CreationView.js
  src-web/components/modules/PolicyStatusView.js
  src-web/containers/AllPolicies.js
  src-web/containers/App.js
  src-web/containers/CreationTab.js
  src-web/containers/GrcRouter.js
  src-web/containers/PoliciesTab.js
  src-web/containers/PolicyDetailSubRouter.js
  src-web/containers/PolicyDetailsTab.js
  src-web/containers/PolicyStatusHistoryTab.js
  src-web/containers/PolicyStatusTab.js
  src-web/containers/PolicyTemplateDetails.js
  src-web/containers/PolicyTemplateTab.js
  src-web/containers/Welcome.js
  src-web/reducers/index.js
  src-web/reducers/user.js
  tests/cypress/support/commands.js
  tests/cypress/support/tests.js
  tests/cypress/support/views.js
  tests/cypress/tests/InvalidYaml_governance.spec.js
  tests/cypress/tests/Verify_URLs_for_policy.spec.js
  tests/cypress/tests/create_policy_field_validation.spec.js
  tests/cypress/tests/issue3677_wrong_namespaceSelector.spec.js
  tests/cypress/tests/policy_YAML_templates_verification.spec.js
  tests/cypress/tests/policy_form_update_per_YAML.spec.js
  tests/jest/components/common/TemplateEditor/TemplateEditor.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/components/common/__snapshots__/Page.test.js.snap
  tests/jest/components/modules/CreationView.test.js
  tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/containers/CreationTab.test.js
  tests/jest/containers/GrcRouter.test.js
  tests/jest/containers/PoliciesTab.test.js
  tests/jest/containers/PolicyDetailSubRouter.test.js
  tests/jest/containers/PolicyStatusTab.test.js
  tests/jest/containers/PolicyTemplateTab.test.js
  tests/jest/containers/Welcome.test.js
  tests/jest/containers/__snapshots__/CreationTab.test.js.snap
  tests/jest/containers/__snapshots__/GrcRouter.test.js.snap
  tests/jest/containers/__snapshots__/PoliciesTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyDetailSubRouter.test.js.snap
  tests/jest/containers/__snapshots__/PolicyDetailsTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyStatusHistoryTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyStatusTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyTemplateDetails.test.js.snap
  tests/jest/containers/__snapshots__/PolicyTemplateTab.test.js.snap
  tests/jest/containers/__snapshots__/Welcome.test.js.snap
  tests/jest/reducers/user.test.js
Labels: approved, lgtm

#543 remove policy cluster drill down from placement rule
  jest.config.js
  scss/policy-yaml-tab.scss
  scss/refresh-time-select.scss
  scss/resource-overview.scss
  scss/resource-toolbar.scss
  scss/secondary-header.scss
  scss/table.scss
  src-web/components/common/RefreshTimeSelect.js
  src-web/components/common/ResourceToolbar.js
  src-web/components/common/StructuredListModuleWithActions.js
  src-web/components/modules/PolicyClusterDetail.js
  src-web/components/modules/PolicyTemplatesView.js
  src-web/components/modules/SecondaryHeader.js
  src-web/containers/App.js
  src-web/containers/PolicyDetailsByCluster.js
  tests/cypress/support/commands.js
  tests/cypress/support/tests.js
  tests/cypress/support/views.js
  tests/jest/components/common/RefreshTimeSelect.test.js
  tests/jest/components/common/ResourceToolbar.test.js
  tests/jest/components/common/__snapshots__/RefreshTimeSelect.test.js.snap
  tests/jest/components/common/__snapshots__/ResourceToolbar.test.js.snap
  tests/jest/components/modules/PolicyClusterDetail.test.js
  tests/jest/components/modules/PolicyTemplates.test.js
  tests/jest/components/modules/SecondaryHeader.test.js
  tests/jest/components/modules/__snapshots__/PolicyClusterDetail.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyTemplates.test.js.snap
  tests/jest/components/modules/__snapshots__/SecondaryHeader.test.js.snap
  tests/jest/containers/PolicyDetailsByCluster.test.js
  tests/jest/containers/__snapshots__/PolicyDetailsByCluster.test.js.snap
Labels: approved, lgtm

#544 Initial implementation of edit policy page
  build/rbac-setup.sh
  jest.config.js
  lib/client/queries.js
  nls/platform.properties
  scss/common.scss
  scss/grc-toggle-module.scss
  scss/grc-view.scss
  scss/policy-details-overview.scss
  scss/policy-status-history.scss
  scss/policy-status-view.scss
  scss/policy-template-details.scss
  src-web/components/common/ResourceTableRowMenuItemActions.js
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/scss/template-editor.scss
  src-web/components/common/TemplateEditor/utils/update-controls.js
  src-web/components/common/YamlEditor.js
  src-web/components/modules/CreationView.js
  src-web/containers/App.js
  src-web/containers/CreationTab.js
  tests/cypress/tests/Verify_URLs_for_policy.spec.js
  tests/jest/components/common/ResourceTableRowMenuItemActions.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/components/common/__snapshots__/ResourceTableRowMenuItemActions.test.js.snap
  tests/jest/components/common/__snapshots__/YamlEditor.test.js.snap
  tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/containers/CreationTab.test.js
  tests/jest/containers/__snapshots__/CreationTab.test.js.snap
Labels: approved, lgtm

#545 lock cypress version
  Dockerfile.e2etest
Labels: approved, lgtm

#546 upgrade cypress to 7.0.0
  Dockerfile.e2etest
  build/cluster-clean-up.sh
  package-lock.json
  package.json
  tests/cypress/config/issue7520/create_namespace_raw.yaml
  tests/cypress/config/issue7520/create_test_issuer.yaml
  tests/cypress/config/issue7520/violation-patterns.yaml
  tests/cypress/support/commands.js
  tests/cypress/support/views.js
  tests/cypress/tests/CertPolicy_governance.spec.js
  tests/cypress/tests/issue7520_added_removed_namespaces.spec.js
Labels: approved, lgtm

#547 "launch cluster" option on cluster violations page should not be available to an imported cluster
  src-web/components/modules/GrcToggleModule.js
Labels: approved, lgtm

#550 remove duplicated refetch from <Query>
  src-web/containers/PoliciesTab.js
  src-web/containers/PolicyDetailsTab.js
  src-web/containers/PolicyStatusHistoryTab.js
  src-web/containers/PolicyStatusTab.js
  src-web/containers/PolicyTemplateDetails.js
  tests/jest/containers/__snapshots__/PolicyDetailsTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyStatusHistoryTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyTemplateDetails.test.js.snap
Labels: approved, lgtm

#551 fix an issue where the call was being sent twice
  src-web/components/common/ResourceTableRowMenuItemActions.js
  src-web/components/modules/GrcToggleModule.js
  src-web/components/modules/GrcView.js
  src-web/containers/PolicyDetailsTab.js
  src-web/containers/PolicyStatusHistoryTab.js
  src-web/containers/PolicyStatusTab.js
  src-web/containers/PolicyTemplateDetails.js
  tests/jest/components/common/ResourceTableRowMenuItemActions.test.js
  tests/jest/components/common/__snapshots__/ResourceTableRowMenuItemActions.test.js.snap
  tests/jest/containers/__snapshots__/PolicyDetailsTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyStatusHistoryTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyStatusTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyTemplateDetails.test.js.snap
Labels: approved, lgtm

#554 wait until create policy button become clickable
  tests/cypress/support/commands.js
Labels: approved, lgtm

#555 remove-depreciated-filter-view
  nls/platform.properties
  package-lock.json
  package.json
  scss/resource-filter-view.scss
  src-web/components/common/ResourceFilterView.js
  tests/jest/components/common/ResourceFilterView.test.js
  tests/jest/components/common/__snapshots__/ResourceFilterView.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#556 correct categories/controls for Compliance operator policy
  src-web/components/common/templates/spec-comp-operator.yaml
  tests/cypress/config/policy_YAML_templates_verification/ComplianceOperator-raw.yaml
Labels: approved, lgtm

#549 move welcome page test to grc
  tests/cypress/support/welcome.js
  tests/cypress/tests/welcomePage.spec.js
Labels: approved, lgtm

#558 edit policy improvements
  src-web/components/common/CheckUserPermission.js
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/utils/update-controls.js
  src-web/components/modules/CreationView.js
  src-web/components/modules/GrcView.js
  src-web/components/modules/PolicyStatusView.js
  src-web/containers/App.js
  src-web/containers/CreationTab.js
  src-web/containers/PoliciesTab.js
  src-web/containers/PolicyDetailsTab.js
  src-web/containers/PolicyStatusTab.js
  tests/cypress/config/policy_YAML_templates_verification/CertificatePolicy-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/ComplianceOperator-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/EtcdEncryption-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/GatekeeperOperator-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/IamPolicy-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/ImageManifestVulnPolicy-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/LimitRange-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/Namespace-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/Pod-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/PodSecurityPolicy-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/Role-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/RoleBinding-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/SecurityContextConstraints-raw.yaml
  tests/cypress/config/verify_YAML_stability/Gatekeeper-template-verify.yaml
  tests/cypress/config/verify_YAML_stability/LimitRange_template-verify.yaml
  tests/cypress/support/commands.js
  tests/cypress/support/tests.js
  tests/jest/containers/PolicyDetailsTab.test.js
  tests/jest/containers/PolicyStatusTab.test.js
  tests/jest/containers/__snapshots__/PolicyDetailsTab.test.js.snap
  tests/jest/containers/__snapshots__/PolicyStatusTab.test.js.snap
Labels: approved, lgtm

#561 Address CVE-2020-28469
  package-lock.json
Labels: approved, lgtm

#560 update namespace replacement
  tests/cypress/tests/issue3677_wrong_namespaceSelector.spec.js
Labels: approved, lgtm

#565 ignore failure
  build/rbac-setup.sh
Labels: approved, lgtm

#566 update nginx image
  src-web/components/common/templates/spec-pod-exists.yaml
  tests/cypress/config/InvalidYamlTests/InvalidIndentation.yaml
  tests/cypress/config/InvalidYamlTests/InvalidPolicyName.yaml
  tests/cypress/config/InvalidYamlTests/MissingNamespace.yaml
  tests/cypress/config/Pod_governance/Pod_specification_cleanup_policy_raw.yaml
  tests/cypress/config/duplicatePolicyInDiffNS/pod_template_duplicate.yaml
  tests/cypress/config/duplicatePolicyInDiffNS/pod_template_original.yaml
  tests/cypress/config/issue2444/pod_policy_raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/Pod-raw.yaml
  tests/jest/components/ComponentsTestingData.js
  tests/jest/components/common/CommonTestingData.js
  tests/jest/components/common/__snapshots__/FormatTableData.test.js.snap
  tests/jest/components/modules/ModuleTestingData.js
  tests/jest/components/modules/__snapshots__/GrcCardsModule.test.js.snap
  tests/jest/components/modules/__snapshots__/GrcView.test.js.snap
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
  tests/jest/containers/data/POLICY_TEMPLATE_DETAILS_QUERY_DATA.js
Labels: approved, lgtm

#568 Address CVE
  package-lock.json
Labels: approved, lgtm

#557 [release-2.2] correct categories/controls for Compliance operator policy
  src-web/components/common/templates/spec-comp-operator.yaml
  tests/e2e/yaml/create_policy/ComplianceOperator_template.yaml
Labels: do-not-merge/hold

#553 [release-2.2] "launch cluster" option on cluster violations page should not be available to an imported cluster""
  src-web/components/modules/GrcToggleModule.js
Labels: do-not-merge/hold

#559 [release-2.2] Address CVEs
  package-lock.json
  package.json
Labels: do-not-merge/hold

#567 upgrade to webpack 5
  package-lock.json
  package.json
  webpack.config.js
  webpack.dll.js
Labels: approved, lgtm

#562 Patternfly filter chip
  Dockerfile.e2etest
  jest.config.js
  lib/client/resource-helper.js
  package-lock.json
  package.json
  scss/modal.scss
  src-web/components/common/ResourceFilterBar.js
  src-web/components/modals/ResourceModal.js
  tests/jest/components/common/ResourceFilterBar.test.js
  tests/jest/components/common/__snapshots__/ResourceFilterBar.test.js.snap
  tests/jest/lib/client/__snapshots__/resource-helper.test.js.snap
  tests/jest/lib/client/resource-helper.test.js
Labels: approved, lgtm

#569 TemplateEditor replace carbon with patternfly
  nls/platform.properties
  scss/no-resource.scss
  src-web/components/common/Icons.js
  src-web/components/common/NoResource.js
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/scss/template-editor.scss
  tests/cypress/support/tests.js
  tests/cypress/support/views.js
  tests/cypress/tests/InvalidYaml_governance.spec.js
  tests/cypress/tests/create_policy_field_validation.spec.js
  tests/cypress/tests/create_policy_multiselect_sanity.spec.js
  tests/cypress/tests/verify_YAML_stability.spec.js
  tests/jest/components/common/Icons.test.js
  tests/jest/components/common/TemplateEditor/TemplateEditor.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/components/common/__snapshots__/Icons.test.js.snap
  tests/jest/components/modules/CreationView.test.js
  tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved, lgtm

#570 enhance e2e test to cover header
  tests/cypress/support/welcome_and_header.js
  tests/cypress/tests/welcomePage_and_Header.spec.js
Labels: approved, lgtm

#572 update ui components to have 1 version call
  package-lock.json
  package.json
  tests/cypress/support/welcome_and_header.js
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
  tests/jest/containers/__snapshots__/PolicyDetailsTab.test.js.snap
  webpack.config.js
Labels: approved, lgtm

#573 check the first icon when running test simutaneously
  tests/cypress/support/views.js
Labels: approved, lgtm

#574 fix wrong logic
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#571 Update cluster status list
  jest.config.js
  lib/client/resource-helper.js
  nls/platform.properties
  src-web/components/common/PatternFlyTable.js
  src-web/components/common/StatusField.js
  src-web/components/modules/PolicyDetailsOverview.js
  src-web/components/modules/PolicyStatusView.js
  src-web/containers/AcmGrcPage.js
  src-web/containers/App.js
  src-web/containers/CreationTab.js
  src-web/containers/PolicyDetailsTab.js
  src-web/containers/definitions/PageDefinitions.js
  src-web/tableDefinitions/hcm-compliances.js
  tests/cypress/support/commands.js
  tests/cypress/support/tests.js
  tests/cypress/support/views.js
  tests/cypress/tests/demos/policy-demo.spec.js
  tests/jest/components/common/CommonTestingData.js
  tests/jest/components/common/ResourceTableRowExpandableTable.test.js
  tests/jest/components/common/__snapshots__/ResourceTableModuleFromProps.test.js.snap
  tests/jest/components/common/__snapshots__/ResourceTableRowExpandableTable.test.js.snap
  tests/jest/components/modules/PolicyDetailsOverview.test.js
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyStatusHistoryView.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/containers/ContainersTestingData.js
  tests/jest/containers/PolicyDetailsTab.test.js
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
  tests/jest/containers/__snapshots__/PolicyDetailsTab.test.js.snap
  tests/jest/tableDefinitions/__snapshots__/hcm-compliances.test.js.snap
  tests/jest/tableDefinitions/hcm-compliances.test.js
Labels: approved, dco-signoff: yes, lgtm

#577 did not use hardcoded namespace when getting the acm route
  build/run-docker-tests.sh
  build/run-e2e-tests.sh
  tests/cypress/start_cypress_tests.sh
Labels: approved, dco-signoff: yes, lgtm

#578 INITIAL_POLL_INTERVAL variable name change
  lib/shared/constants.js
  src-web/containers/AcmGrcPage.js
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#579 revert webpack 5 upgrade as it breaks monaco editor hover tooltip
  package-lock.json
  package.json
  webpack.config.js
  webpack.dll.js
Labels: approved, dco-signoff: yes, lgtm

#580 support to use cluster token login during the test
  build/run-docker-tests.sh
  tests/cypress/start_cypress_tests.sh
Labels: approved, dco-signoff: yes, lgtm

#581 show notification when errored after close
  .gitignore
  fonts/RedHatText/RedHatText-Bold.eot
  fonts/RedHatText/RedHatText-Bold.woff
  fonts/RedHatText/RedHatText-Bold.woff2
  fonts/RedHatText/RedHatText-BoldItalic.eot
  fonts/RedHatText/RedHatText-BoldItalic.woff
  fonts/RedHatText/RedHatText-BoldItalic.woff2
  fonts/RedHatText/RedHatText-Italic.eot
  fonts/RedHatText/RedHatText-Italic.woff
  fonts/RedHatText/RedHatText-Italic.woff2
  fonts/RedHatText/RedHatText-Medium.eot
  fonts/RedHatText/RedHatText-Medium.woff
  fonts/RedHatText/RedHatText-Medium.woff2
  fonts/RedHatText/RedHatText-MediumItalic.eot
  fonts/RedHatText/RedHatText-MediumItalic.woff
  fonts/RedHatText/RedHatText-MediumItalic.woff2
  fonts/RedHatText/RedHatText-Regular.eot
  fonts/RedHatText/RedHatText-Regular.woff
  fonts/RedHatText/RedHatText-Regular.woff2
  scss/common.scss
  scss/resource-filterbar.scss
  src-web/components/common/DangerNotification.js
  src-web/components/common/ResourceFilterBar.js
  src-web/components/common/ScrollToTop.js
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/scss/template-editor.scss
  src-web/components/modules/GrcView.js
  src-web/containers/AcmGrcPage.js
  src-web/containers/CreationTab.js
  src-web/index.js
  tests/cypress/config/clusters.yaml
  tests/cypress/support/views.js
  tests/jest/components/common/ScrollToTop.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/components/common/__snapshots__/ResourceFilterBar.test.js.snap
  tests/jest/components/common/__snapshots__/ScrollToTop.test.js.snap
  tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
  webpack.config.js
  webpack.dll.js
Labels: approved, dco-signoff: yes, lgtm

#576 Cluster list - Tests
  README.md
  cypressEnvConfig.yaml
  lib/client/design-helper.js
  lib/client/resource-helper.js
  package-lock.json
  src-web/components/common/PatternFlyTable.js
  src-web/components/modules/PolicyStatusView.js
  src-web/containers/AcmGrcPage.js
  src-web/tableDefinitions/hcm-compliances.js
  tests/cypress/start_cypress_tests.sh
  tests/cypress/support/commands.js
  tests/cypress/support/tests.js
  tests/cypress/support/views.js
  tests/jest/components/modules/PolicyDetailsOverview.test.js
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
  tests/jest/tableDefinitions/__snapshots__/hcm-compliances.test.js.snap
  tests/jest/tableDefinitions/hcm-compliances.test.js
  views/home.handlebars
Labels: approved, dco-signoff: yes, lgtm

#585 should use regex for clusterStatus
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#586 fix e2e image
  Dockerfile.e2etest
Labels: approved, dco-signoff: yes, lgtm

#587 disable coverage by default and enable it in grc-ui travis
  build/run-e2e-tests.sh
  tests/cypress/start_cypress_tests.sh
Labels: approved, dco-signoff: yes, lgtm

#589 Update cluster list style - 7208
  src-web/components/common/StatusField.js
  src-web/containers/App.js
  src-web/containers/Welcome.js
  src-web/scss/common.scss
  src-web/scss/policy-details-overview.scss
  src-web/scss/welcome.scss
  src-web/tableDefinitions/hcm-compliances.js
  tests/cypress/support/views.js
  tests/jest/components/common/__snapshots__/StatusField.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/containers/__snapshots__/Welcome.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#590 fix multi-line yaml handling and parsing
  package-lock.json
  package.json
  src-web/components/common/TemplateEditor/utils/update-controls.js
  src-web/components/common/TemplateEditor/utils/update-editor.js
  src-web/components/modules/PolicyTemplateDetailsView.js
  tests/cypress/config/policy_YAML_templates_verification/GatekeeperOperator-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/Pod-raw.yaml
  tests/cypress/config/policy_YAML_templates_verification/SecurityContextConstraints-raw.yaml
  tests/cypress/config/verify_YAML_stability/Gatekeeper-template-verify.yaml
  tests/cypress/config/verify_YAML_stability/LimitRange_template-verify.yaml
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#592 Use RegEx to account for trailing comma in cluster list
  package-lock.json
  src-web/scss/policy-details-overview.scss
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#593 upgrade cypress to 7.2.0
  Dockerfile.e2etest
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm
