Repository stolostron/grc-ui, pull requests merged in 2021-03, with the labels that each got.

#481 add test for summary table - Polarion TC RHACM4K-2343
  tests/cypress/config/all_policies_summary_table/policy-config.yaml
  tests/cypress/support/commands.js
  tests/cypress/tests/all_policies_summary_table.spec.js
Labels: approved, lgtm

#495 Upgrade Elliptic package - 10261
  package-lock.json
Labels: approved, lgtm

#491 Update toggle styling - 8648
  scss/grc-toggle-module.scss
  scss/pattern-fly-table.scss
  src-web/components/modules/GrcToggleModule.js
Labels: approved, lgtm

#498 introduce way of loosening checks when testsuite not run standalone
  tests/cypress/common/tests.js
  tests/cypress/common/views.js
  tests/cypress/support/commands.js
  tests/cypress/tests/all_policies_summary_table.spec.js
Labels: approved

#501 log $STANDALONE_TESTSUITE_EXECUTION value in start_cypress_tests.sh
  tests/cypress/start_cypress_tests.sh
Labels: approved, lgtm

#502 Update e2e Dockerfile
  Dockerfile.e2etest
  build/run-docker-tests.sh
  package.json
Labels: approved

#503 Add typescript to test image
  Dockerfile.e2etest
Labels: approved

#494 policy with a long name not working properly
  nls/platform.properties
  package-lock.json
  package.json
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/utils/validate-yaml.js
  tests/cypress/config/InvalidYamlTests/invalidYamlErrors.yaml
  tests/e2e/all-policy-page.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved

#480 [release-2.2] add back gatekeeper operator policy
  src-web/components/common/templates/index.js
  src-web/components/common/templates/spec-gatekeeper.yaml
  tests/e2e/yaml/create_policy/GatekeeperOperator_template.yaml
Labels: lgtm

#500 Replace main builds with cron
  .travis.yml
Labels: approved

#506 use the default channel for the compliance operator
  src-web/components/common/templates/spec-comp-operator.yaml
  tests/cypress/config/policy_YAML_templates_verification/ComplianceOperator-raw.yaml
  tests/e2e/yaml/create_policy/ComplianceOperator_template.yaml
Labels: approved, lgtm

#508 [release-2.2] use the default channel for the compliance operator
  src-web/components/common/templates/spec-comp-operator.yaml
  tests/e2e/yaml/create_policy/ComplianceOperator_template.yaml
Labels: lgtm

#510 remove redundant nightwatch tests
  tests/e2e/all-policy-page.test.js.bk
  tests/e2e/disable.test.js.bk
Labels: approved, lgtm

#507 Not being redirected to policy listing after a policy update
  lib/client/queries.js
  package-lock.json
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/containers/CreationTab.js
Labels: approved, lgtm

#511 policy name length restriction seems to be one off
  nls/platform.properties
  package-lock.json
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/utils/validate-yaml.js
  tests/cypress/config/InvalidYamlTests/invalidYamlErrors.yaml
  tests/cypress/tests/create_policy_field_validation.spec.js
  tests/e2e/all-policy-page.test.js.bk
  tests/e2e/rbac.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/config/platform-properties.json
Labels: approved

#513 Set YAML parse error object directly
  src-web/components/common/TemplateEditor/components/YamlParser.js
Labels: approved, lgtm

#509 Remediation consistency - 9238
  build/run-docker-tests.sh
  lib/client/queries.js
  nls/platform.properties
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/scss/template-editor.scss
  src-web/components/common/TemplateEditor/utils/update-editor.js
  src-web/components/common/templates/policy-template.hbs
  src-web/components/modules/CreationView.js
  src-web/tableDefinitions/hcm-compliances.js
  tests/cypress/common/tests.js
  tests/cypress/common/views.js
  tests/cypress/config/IamPolicy_governance/policy-config.yaml
  tests/cypress/config/ImageManifest_governance/policy-config.yaml
  tests/cypress/config/LimitRange_governance/policy-config.yaml
  tests/cypress/config/Namespace_governance/policy-config.yaml
  tests/cypress/config/PodSecurityPolicy_governance/policy-config.yaml
  tests/cypress/config/Pod_governance/policy-config.yaml
  tests/cypress/config/RoleBinding_policy_governance/policy-config.yaml
  tests/cypress/config/Role_policy_governance/policy-config.yaml
  tests/cypress/config/SCC_policy_governance/policy-config.yaml
  tests/cypress/config/all_policies_summary_table/policy-config.yaml
  tests/cypress/config/certPolicyTest/test_certpolicy_config.yaml
  tests/cypress/config/demos/policy-demo/demo-policy-config.yaml
  tests/cypress/config/demos/two_policies/policy-config.yaml
  tests/cypress/config/demos/two_specs/policy-config.yaml
  tests/cypress/config/encryPolicyTest/test_etcdencryption_config.yaml
  tests/cypress/config/issue3677/policy-config.yaml
  tests/cypress/config/policy_YAML_templates_verification/policy-config.yaml
  tests/cypress/config/policy_form_update_per_YAML/policy-config.yaml
  tests/cypress/support/commands.js
  tests/cypress/tests/CertPolicy_governance.spec.js
  tests/cypress/tests/DuplicatePolicyInDiffNS.spec.js
  tests/cypress/tests/demos/policy-demo.spec.js
  tests/cypress/tests/verify_YAML_stability.spec.js
  tests/jest/components/common/CommonTestingData.js
  tests/jest/components/common/TemplateEditor/TemplateEditor.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/components/modules/ModuleTestingData.js
  tests/jest/components/modules/PolicyTemplates.test.js
  tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyClusterDetail.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/config/platform-properties.json
  tests/jest/containers/ContainersTestingData.js
  tests/jest/containers/__snapshots__/PolicyDetailsByCluster.test.js.snap
Labels: approved

#512 tag selected tests with "extended" cypress tag
  tests/cypress/tests/LimitRange_governance.spec.js
  tests/cypress/tests/Namespace_governance.spec.js
  tests/cypress/tests/PodSecurityPolicy_governance.spec.js
  tests/cypress/tests/RoleBindingPolicy_governance.spec.js
  tests/cypress/tests/RolePolicy_governance.spec.js
  tests/cypress/tests/SCCPolicy_governance.spec.js
Labels: approved

#516 Fix when namespace is not provided - 10640
  src-web/components/common/TemplateEditor/TemplateEditor.js
  tests/jest/components/common/TemplateEditor/TemplateEditor.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
Labels: approved

#515 increase retry time in waitForDocumentUpdate() for better test stability
  tests/cypress/common/views.js
  tests/cypress/support/commands.js
Labels: approved

#517 upgrade cypress to latest
  Dockerfile.e2etest
  package-lock.json
  package.json
Labels: approved

#521 trigger rebuild
  README.md
Labels: approved, lgtm

#523 update ssri to 8.0.1
  package-lock.json
Labels: approved, lgtm

#522 add doTableSearch() and clearTableSearch() commands
  tests/cypress/common/views.js
  tests/cypress/support/commands.js
Labels: approved, lgtm

#527 fix ssri inconsistency
  package-lock.json
Labels: approved

#524 add action_ prefix to doTableSearch() and clearTableSearch() functions
  tests/cypress/common/views.js
  tests/cypress/support/commands.js
Labels: approved, lgtm

#526 removed cypress-tags; added custom test tagging mechanism
  package-lock.json
  package.json
  tests/cypress/plugins/index.js
  tests/cypress/start_cypress_tests.sh
  tests/cypress/support/tagging.js
  tests/cypress/tests/CertPolicy_governance.spec.js
  tests/cypress/tests/DuplicatePolicyInDiffNS.spec.js
  tests/cypress/tests/IamPolicy_governance.spec.js
  tests/cypress/tests/ImageManifest_governance.spec.js
  tests/cypress/tests/InvalidYaml_governance.spec.js
  tests/cypress/tests/LimitRange_governance.spec.js
  tests/cypress/tests/Namespace_governance.spec.js
  tests/cypress/tests/PodSecurityPolicy_governance.spec.js
  tests/cypress/tests/Pod_governance.spec.js
  tests/cypress/tests/RoleBindingPolicy_governance.spec.js
  tests/cypress/tests/RolePolicy_governance.spec.js
  tests/cypress/tests/SCCPolicy_governance.spec.js
  tests/cypress/tests/Verify_URLs_for_policy.spec.js
  tests/cypress/tests/all_policies_summary_table.spec.js
  tests/cypress/tests/create_policy_field_validation.spec.js
  tests/cypress/tests/create_policy_multiselect_sanity.spec.js
  tests/cypress/tests/issue2444_empty_namespace_list_in_configurationPolicy.spec.js
  tests/cypress/tests/issue3677_wrong_namespaceSelector.spec.js
  tests/cypress/tests/issue7520_added_removed_namespaces.spec.js
  tests/cypress/tests/policy_YAML_templates_verification.spec.js
  tests/cypress/tests/policy_form_update_per_YAML.spec.js
  tests/cypress/tests/verify_YAML_stability.spec.js
Labels: approved

#528 only run nightwatch in extended phase in canary
  build/run-docker-tests.sh
  tests/cypress/tests/Pod_governance.spec.js
Labels: approved

#529 fix docker image run scripts
  Dockerfile.e2etest
  build/run-docker-tests.sh
Labels: approved

#525 Initial implementation of selected RBAC test scenarios
  tests/cypress/common/tests.js
  tests/cypress/common/views.js
  tests/cypress/config/RBAC/permissions.json
  tests/cypress/config/RBAC/policy-config.yaml
  tests/cypress/start_cypress_tests.sh
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tests/cypress/tests/RBAC.spec.js
  tests/cypress/tests/Verify_URLs_for_policy.spec.js
  tests/e2e/rbac.test.js.bk
Labels: approved

#532 wait to redirect until useraccess is loaded
  src-web/containers/CreationTab.js
Labels: approved

#533 add RBAC tests for policy Creation and Removal
  tests/cypress/common/tests.js
  tests/cypress/config/RBAC/policy-config.yaml
  tests/cypress/support/commands.js
  tests/cypress/tests/RBAC.spec.js
Labels: approved, lgtm

#534 move /cypress/common to /cypress/support
  tests/cypress/support/commands.js
  tests/cypress/support/tests.js
  tests/cypress/support/views.js
  tests/cypress/tests/CertPolicy_governance.spec.js
  tests/cypress/tests/DuplicatePolicyInDiffNS.spec.js
  tests/cypress/tests/IamPolicy_governance.spec.js
  tests/cypress/tests/ImageManifest_governance.spec.js
  tests/cypress/tests/InvalidYaml_governance.spec.js
  tests/cypress/tests/LimitRange_governance.spec.js
  tests/cypress/tests/Namespace_governance.spec.js
  tests/cypress/tests/PodSecurityPolicy_governance.spec.js
  tests/cypress/tests/Pod_governance.spec.js
  tests/cypress/tests/RBAC.spec.js
  tests/cypress/tests/RoleBindingPolicy_governance.spec.js
  tests/cypress/tests/RolePolicy_governance.spec.js
  tests/cypress/tests/SCCPolicy_governance.spec.js
  tests/cypress/tests/Verify_URLs_for_policy.spec.js
  tests/cypress/tests/create_policy_multiselect_sanity.spec.js
  tests/cypress/tests/demos/ImageManifest_governance.spec.js
  tests/cypress/tests/demos/policy-demo.spec.js
  tests/cypress/tests/demos/two_policies.spec.js
  tests/cypress/tests/demos/two_specs_policy.spec.js
  tests/cypress/tests/demos/violations-demo.spec.js
  tests/cypress/tests/issue2444_empty_namespace_list_in_configurationPolicy.spec.js
  tests/cypress/tests/issue3677_wrong_namespaceSelector.spec.js
  tests/cypress/tests/issue7520_added_removed_namespaces.spec.js
  tests/cypress/tests/verify_YAML_stability.spec.js
Labels: approved, lgtm

#535 add waituntil on local cluster button click
  scss/resource-toolbar.scss
  tests/cypress/support/commands.js
Labels: approved, lgtm

#536 update ui components
  package-lock.json
  package.json
  scss/common.scss
Labels: approved, lgtm

#531 Update modal from new header
  jest.config.js
  package-lock.json
  package.json
  scss/modal.scss
  src-web/components/modals/PolicyActionModal.js
  src-web/components/modals/RemoveResourceModal.js
  src-web/components/modals/ResourceModal.js
  src-web/components/modules/GrcView.js
  src-web/components/modules/PolicyClusterDetail.js
  src-web/components/modules/PolicyTemplatesView.js
  tests/cypress/support/commands.js
  tests/cypress/support/views.js
  tests/jest/components/modals/PolicyActionModal.test.js
  tests/jest/components/modals/__snapshots__/PolicyActionModal.test.js.snap
  tests/jest/components/modals/__snapshots__/RemoveResourceModal.test.js.snap
  tests/jest/components/modals/__snapshots__/ResourceModal.test.js.snap
  tests/jest/components/modules/GrcView.test.js
  tests/jest/components/modules/__snapshots__/GrcView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyClusterDetail.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyTemplates.test.js.snap
Labels: approved, lgtm
