Repository stolostron/grc-ui, pull requests merged in 2021-05, with the labels that each got.

#594 fix favicon in GRC and Welcome
  src-web/graphics/RHACM-Favicon.svg
Labels: approved, dco-signoff: yes, lgtm

#597 attempt to fix flaky logout for localhost
  tests/cypress/support/commands.js
Labels: approved, dco-signoff: yes, lgtm

#595 Change expandedText from default 'Show Less' to 'Show Fewer'
  src-web/tableDefinitions/hcm-compliances.js
Labels: approved, dco-signoff: yes, lgtm

#598 Remove hcm-compliances
  src-web/components/modules/PolicyDetailsOverview.js
  src-web/reducers/common.js
  src-web/tableDefinitions/grcPoliciesViewDef.js
  src-web/tableDefinitions/hcm-compliances.js
  src-web/tableDefinitions/index.js
  src-web/tableDefinitions/policyDetailsClusterListDef.js
  src-web/tableDefinitions/policyDetailsOverviewDef.js
  src-web/tableDefinitions/utils.js
  src-web/utils/resource-helper.js
  src-web/utils/resource-schema.js
  src-web/utils/table-helper.js
  tests/jest/reducers/common.test.js
  tests/jest/tableDefinitions/__snapshots__/index.test.js.snap
  tests/jest/tableDefinitions/__snapshots__/utils.test.js.snap
  tests/jest/tableDefinitions/index.test.js
  tests/jest/tableDefinitions/utils.test.js
  tests/jest/utils/__snapshots__/resource-helper.test.js.snap
  tests/jest/utils/resource-helper.test.js
  tests/jest/utils/table-helper.test.js
Labels: approved, dco-signoff: yes, lgtm

#596 don't show compliant icon when none of policies returns status for the cluster
  src-web/tableDefinitions/utils.js
Labels: approved, dco-signoff: yes, lgtm

#599 Fix code smells from PR 598
  src-web/tableDefinitions/utils.js
  tests/jest/tableDefinitions/__snapshots__/utils.test.js.snap
  tests/jest/tableDefinitions/utils.test.js
Labels: approved, dco-signoff: yes, lgtm

#600 reload page to ensure delete is properly performed
  src-web/scss/common.scss
  tests/cypress/tests/DuplicatePolicyInDiffNS.spec.js
Labels: approved, dco-signoff: yes, lgtm

#582 upgrade to webpack 5
  package-lock.json
  package.json
  webpack.config.js
  webpack.dll.js
Labels: approved, dco-signoff: yes, lgtm

#601 update ui components
  package-lock.json
  package.json
  src-web/containers/AcmGrcPage.js
  tests/cypress/support/welcome_and_header.js
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#607 prevent cypress from failing the test due to uncaught exception
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
Labels: approved, dco-signoff: yes, lgtm

#608 update tooltip icons
  package-lock.json
  package.json
  src-web/components/common/Icons.js
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/components/YamlEditor.js
  src-web/components/common/YamlEditor.js
  tests/cypress/support/views.js
  tests/jest/components/common/Icons.test.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/components/common/__snapshots__/Icons.test.js.snap
  tests/jest/components/common/__snapshots__/StatusField.test.js.snap
  tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyTemplateDetailsView.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#609 rename left nav and page name to Governance
  package-lock.json
  package.json
  src-web/containers/App.js
  src-web/nls/platform.properties
  tests/cypress/support/commands.js
  tests/cypress/support/welcome_and_header.js
  tests/jest/components/ComponentsTestingData.js
  tests/jest/config/platform-properties.json
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
  tests/jest/containers/__snapshots__/Welcome.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#605 Use common ui-components
  README.md
  src-web/components/common/DetailsModule.js
  src-web/components/modules/PolicyDetailsOverview.js
  src-web/components/modules/PolicyStatusHistoryView.js
  src-web/components/modules/PolicyStatusView.js
  src-web/components/modules/PolicyTemplateDetailsView.js
  src-web/scss/common.scss
  src-web/scss/policy-details-overview.scss
  src-web/scss/policy-status-view.scss
  src-web/tableDefinitions/policyDetailsClusterListDef.js
  src-web/tableDefinitions/relatedObjectsDef.js
  src-web/tableDefinitions/statusByClustersDef.js
  src-web/tableDefinitions/statusByTemplatesDef.js
  src-web/tableDefinitions/statusHistoryDef.js
  src-web/tableDefinitions/utils.js
  tests/cypress/support/commands.js
  tests/cypress/support/views.js
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyStatusHistoryView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyStatusView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyTemplateDetailsView.test.js.snap
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#611 prepare for prow onboarding
  .dockerignore
  .travis.yml
  Dockerfile
  Makefile
  build/build.sh
Labels: approved, dco-signoff: yes, lgtm

#612 fix lint-unittest-sonarcloud
  .travis.yml
  Dockerfile
  Dockerfile.e2etest
  Makefile
  Makefile.prow
  build/Configfile
  build/run-e2e-tests.sh
Labels: approved, dco-signoff: yes, lgtm

#610 upgrade cypress and dependencies
  .babelrc
  Dockerfile.e2etest
  build/run-docker-tests.sh
  package-lock.json
  package.json
  src-web/containers/CreationTab.js
  src-web/scss/common.scss
  src-web/utils/client/queries.js
  tests/jest/components/common/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
  tests/jest/components/common/__snapshots__/Modal.test.js.snap
  tests/jest/components/modules/__snapshots__/CreationView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyStatusView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyTemplateDetailsView.test.js.snap
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#613 add grc-ui-tests image build and publish
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm

#614 [skip ci] fix test image name
  Makefile
Labels: approved, dco-signoff: yes, lgtm

#602 Ansible modal
  jest.config.js
  package-lock.json
  package.json
  src-web/actions/common.js
  src-web/components/common/Modal.js
  src-web/components/common/ResourceTableRowMenuItemActions.js
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/nls/platform.properties
  src-web/reducers/index.js
  src-web/tableDefinitions/grcPoliciesViewDef.js
  src-web/utils/client/apollo-client.js
  src-web/utils/client/queries.js
  src-web/utils/constants.js
  tests/jest/config/platform-properties.json
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, do-not-merge/hold, lgtm

#615 remove publish workaround
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm

#618 use MANAGED_CLUSTER_NAME as default cluster selector when specified
  build/cluster-clean-up.sh
  tests/cypress/config/IamPolicy_governance/policy-clusterrolebinding-cleanup_raw.yaml
  tests/cypress/config/IamPolicy_governance/policy-clusterrolebinding-setup_raw.yaml
  tests/cypress/config/IamPolicy_governance/policy-config.yaml
  tests/cypress/config/ImageManifest_governance/ImageManifest_specification_cleanup_policy_raw.yaml
  tests/cypress/config/ImageManifest_governance/policy-config.yaml
  tests/cypress/config/LimitRange_governance/LimitRange_specification_setup_policy_raw.yaml
  tests/cypress/config/LimitRange_governance/policy-config.yaml
  tests/cypress/config/Namespace_governance/Namespace_specification_cleanup_policy_raw.yaml
  tests/cypress/config/Namespace_governance/Namespace_specification_setup_policy_raw.yaml
  tests/cypress/config/Namespace_governance/policy-config.yaml
  tests/cypress/config/PodSecurityPolicy_governance/PodSecurityPolicy_cleanup_policy_raw.yaml
  tests/cypress/config/PodSecurityPolicy_governance/policy-config.yaml
  tests/cypress/config/Pod_governance/Pod_specification_cleanup_policy_raw.yaml
  tests/cypress/config/Pod_governance/policy-config.yaml
  tests/cypress/config/RBAC/policy-config.yaml
  tests/cypress/config/RoleBinding_policy_governance/policy-config.yaml
  tests/cypress/config/RoleBinding_policy_governance/role_binding_specification_cleanup_policy_raw.yaml
  tests/cypress/config/Role_policy_governance/policy-config.yaml
  tests/cypress/config/Role_policy_governance/role_specification_cleanup_policy_raw.yaml
  tests/cypress/config/SCC_policy_governance/SCC_cleanup_policy_raw.yaml
  tests/cypress/config/SCC_policy_governance/policy-config.yaml
  tests/cypress/config/all_policies_summary_table/policy-config.yaml
  tests/cypress/config/demos/two_policies/role_binding_specification_cleanup_policy_raw.yaml
  tests/cypress/config/demos/two_policies/role_specification_cleanup_policy_raw.yaml
  tests/cypress/config/demos/two_specs/role_binding_specification_cleanup_policy_raw.yaml
  tests/cypress/config/demos/two_specs/role_specification_cleanup_policy_raw.yaml
  tests/cypress/config/duplicatePolicyInDiffNS/create_ns_template.yaml
  tests/cypress/config/duplicatePolicyInDiffNS/pod_template_duplicate.yaml
  tests/cypress/config/duplicatePolicyInDiffNS/pod_template_original.yaml
  tests/cypress/start_cypress_tests.sh
  tests/cypress/support/views.js
Labels: approved, dco-signoff: yes, lgtm

#616 fix-small-bugs-on-ansible-modal
  jest.config.js
  package-lock.json
  package.json
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/nls/platform.properties
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#617 Update title style for template YAML on status page
  package-lock.json
  package.json
  src-web/components/modules/PolicyTemplateDetailsView.js
  src-web/scss/policy-template-details.scss
  tests/jest/components/modules/__snapshots__/PolicyTemplateDetailsView.test.js.snap
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#619 add ansible jobs table
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/nls/platform.properties
  src-web/tableDefinitions/ansibleJobHistoryDef.js
  src-web/tableDefinitions/utils.js
  src-web/utils/client/queries.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes

#620 Sort tables
  package-lock.json
  package.json
  src-web/components/modules/PolicyStatusHistoryView.js
  src-web/components/modules/PolicyStatusView.js
  src-web/components/modules/PolicyTemplateDetailsView.js
  src-web/tableDefinitions/policyDetailsClusterListDef.js
  tests/cypress/support/welcome_and_header.js
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyStatusHistoryView.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyStatusView.test.js.snap
  tests/jest/containers/__snapshots__/AcmGrcPage.test.js.snap
Labels: approved, dco-signoff: yes, lgtm

#624 handling corner cases for status icon
  package-lock.json
  package.json
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/tableDefinitions/ansibleJobHistoryDef.js
  src-web/tableDefinitions/utils.js
Labels: approved, dco-signoff: yes, lgtm

#625 update job history table with link to job
  src-web/components/common/Icons.js
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/nls/platform.properties
  src-web/scss/ansible-modal.scss
  src-web/scss/grc-toggle-module.scss
  src-web/tableDefinitions/ansibleJobHistoryDef.js
  src-web/tableDefinitions/utils.js
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#627 fix transformFunction for ansible job history table
  src-web/tableDefinitions/ansibleJobHistoryDef.js
  src-web/tableDefinitions/utils.js
Labels: approved, dco-signoff: yes, lgtm

#628 parameterize path_to_tests to allow running single test case
  tests/cypress/start_cypress_tests.sh
Labels: approved, dco-signoff: yes, lgtm

#626 Fixed ansible state for create update data flow
  Dockerfile.e2etest
  package-lock.json
  package.json
  src-web/components/common/TitleWithTooltip.js
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/nls/platform.properties
  src-web/scss/ansible-modal.scss
  tests/jest/config/platform-properties.json
Labels: approved, dco-signoff: yes, lgtm

#630 monaco editor tooltips
  src-web/components/common/TemplateEditor/TemplateEditor.js
  src-web/components/common/TemplateEditor/scss/template-editor.scss
  webpack.dll.js
Labels: approved, dco-signoff: yes, lgtm

#631 Add lanuch ansible panel on policy details page
  package-lock.json
  package.json
  src-web/components/common/AutomationButton.js
  src-web/components/modals/AnsibleAutomationModal.js
  src-web/components/modules/PolicyDetailsOverview.js
  src-web/scss/ansible-modal.scss
  src-web/tableDefinitions/policyDetailsOverviewDef.js
  src-web/tableDefinitions/utils.js
  tests/jest/components/common/ TitleWithTooltip.test.js
  tests/jest/components/common/__snapshots__/ TitleWithTooltip.test.js.snap
  tests/jest/components/modules/__snapshots__/PolicyDetailsOverview.test.js.snap
Labels: approved, dco-signoff: yes
